"""n8n workflow, generated rather than hand-drawn.

WHAT n8n IS ALLOWED TO DO HERE

The brief names n8n as the glue, and glue is exactly the right job for it:
receive Bolna's delivery, forward it, fan out on the answer, run the
dispatcher on a schedule, retry transport failures, alert a human. All of
that is routing, and routing is what a visual workflow is good at.

What n8n must not do is decide. Every branch that could create an
appointment stays inside the service, because the rules that make this
system safe are not expressible as nodes: a confidence threshold per slot, a
read-back that clears a value when rejected, an idempotency key that has to
be evaluated under the same lock as the availability check. A workflow can
be edited by anyone with the editor open, has no test suite, and fails in
ways that produce a booking rather than an error. The moment "if confidence
> 0.9" appears in a Switch node, the guarantees in this repository are
decorative.

So the contract is narrow and one-directional: n8n calls
``POST /webhooks/bolna`` and reads ``outcome``. It never posts a booking, it
never reads a slot confidence, and it cannot turn a needs_callback into a
booking no matter how it is wired.

The workflow is generated by this module instead of exported from the n8n
editor so that it can be diffed, reviewed, and asserted about - the tests
below check that no node can book, and that no credential was baked into
the JSON on the way out.

ONE DEPLOYMENT WRINKLE, STATED PLAINLY

Bolna documents no request signature; the protection it offers is that
deliveries originate from its egress address. Putting n8n in the middle
destroys that check, because the address our service sees is n8n's. So the
allowlist becomes "n8n may call us" and Bolna's authenticity rests entirely
on the shared secret that n8n forwards. That is a real reduction in defence
and it is worth knowing about rather than discovering.
"""
from __future__ import annotations

import json
from typing import Any

WORKFLOW_ID = "clinic-receptionist"
WORKFLOW_NAME = "Clinic Voice Receptionist"

# Placeholders resolved by n8n from its own environment, never by this
# generator. Writing a real key into a file that gets committed is how
# secrets end up in git history.
RECEPTIONIST_URL = "={{ $env.RECEPTIONIST_URL }}"
WEBHOOK_SECRET = "={{ $env.BOLNA_WEBHOOK_SECRET }}"
OPS_ALERT_URL = "={{ $env.OPS_ALERT_URL }}"

# Outcomes the service returns. Every one is routed explicitly; there is no
# default branch, because a default is how an outcome added later gets
# silently treated as whatever the first branch happens to be.
OUTCOMES = ("booked", "needs_callback", "escalated", "not_actionable")

DISPATCH_INTERVAL_MINUTES = 15


# Stable UUID for the webhook node. n8n keys the registered production URL on
# `webhookId`, and an imported node without one activates without ever binding
# the path: the workflow reports active and POSTing to it returns
# "webhook is not registered". The editor generates this on node creation, so
# a hand-built workflow has to supply it. Fixed rather than random so
# re-importing keeps the same URL.
BOLNA_WEBHOOK_ID = "6f1e2a7c-3b40-4d21-9c8e-5a7d0b1e4f92"


def _node(name: str, type_: str, position: list[int], parameters: dict[str, Any],
          type_version: int = 1, webhook_id: str | None = None,
          on_error: str | None = None) -> dict[str, Any]:
    node = {
        "parameters": parameters,
        "id": name.lower().replace(" ", "-"),
        "name": name,
        "type": type_,
        "typeVersion": type_version,
        "position": position,
    }
    if webhook_id:
        node["webhookId"] = webhook_id
    if on_error:
        node["onError"] = on_error
    return node


def build_workflow() -> dict[str, Any]:
    """The importable workflow object."""
    nodes: list[dict[str, Any]] = [
        _node(
            "Bolna Post-Call", "n8n-nodes-base.webhook", [-320, 0],
            {
                "httpMethod": "POST",
                "path": "bolna-post-call",
                "responseMode": "responseNode",
                "notes": (
                    "Bolna posts the execution object here after the call ends. "
                    "Restrict this URL to Bolna's egress address at the reverse "
                    "proxy; n8n's own webhook has no signature check either."
                ),
            },
            type_version=2,
            webhook_id=BOLNA_WEBHOOK_ID,
        ),
        _node(
            "Ingest Call", "n8n-nodes-base.httpRequest", [-100, 0],
            {
                "method": "POST",
                "url": f"{RECEPTIONIST_URL}/webhooks/bolna",
                "sendHeaders": True,
                "headerParameters": {"parameters": [
                    {"name": "X-Webhook-Secret", "value": WEBHOOK_SECRET},
                ]},
                "sendBody": True,
                "specifyBody": "json",
                "jsonBody": "={{ JSON.stringify($json.body) }}",
                "options": {"retry": {"retryOnFail": True, "maxTries": 3}},
                "notes": (
                    "The service decides. This node forwards the payload and "
                    "reads the outcome; it must never post a booking itself."
                ),
            },
            type_version=4,
        ),
        _node(
            "Route Outcome", "n8n-nodes-base.switch", [140, 0],
            {
                "rules": {"values": [
                    {
                        "conditions": {"conditions": [{
                            "leftValue": "={{ $json.outcome }}",
                            "rightValue": outcome,
                            "operator": {"type": "string", "operation": "equals"},
                        }]},
                        "outputKey": outcome,
                    }
                    for outcome in OUTCOMES
                ]},
                "options": {"fallbackOutput": "none"},
                "notes": (
                    "No fallback branch on purpose. An outcome added to the "
                    "service later should stop here visibly rather than fall "
                    "into whichever branch happens to be first."
                ),
            },
            type_version=3,
        ),
        _node(
            "Booked", "n8n-nodes-base.noOp", [400, -180],
            {"notes": (
                "Nothing to do. The confirmation WhatsApp was sent by the "
                "service during ingest, and the reminder and review request "
                "are queued for the scheduled dispatch below."
            )},
        ),
        _node(
            "Alert Reception", "n8n-nodes-base.httpRequest", [400, 0],
            {
                "method": "POST",
                "url": OPS_ALERT_URL,
                "sendBody": True,
                "specifyBody": "json",
                "jsonBody": (
                    '={{ JSON.stringify({ "call_id": $json.call_id, '
                    '"outcome": $json.outcome, "reason": $json.reason, '
                    '"unresolved": $json.unresolved }) }}'
                ),
                "options": {"retry": {"retryOnFail": True, "maxTries": 3}},
                "notes": (
                    "needs_callback and escalated both land here. The reason "
                    "names the specific slots that failed, so reception knows "
                    "what to ask instead of replaying the recording."
                ),
            },
            type_version=4,
            # A failed alert must not swallow the acknowledgement. Observed
            # live: when this node errored the run stopped here, the Respond
            # node never fired, and the webhook returned an empty body - so
            # Bolna would retry a call the service had correctly declined,
            # forever. Losing the alert is bad; looping the delivery is worse,
            # and the callback is still recorded in the service either way.
            on_error="continueRegularOutput",
        ),
        _node(
            "Ignore Incomplete Call", "n8n-nodes-base.noOp", [400, 180],
            {"notes": (
                "Ringing, busy or failed executions carry no caller intent. "
                "Nothing to route and nobody to call back."
            )},
        ),
        _node(
            "Acknowledge", "n8n-nodes-base.respondToWebhook", [660, 0],
            {
                "respondWith": "json",
                "responseBody": '={{ JSON.stringify({ "received": true }) }}',
                "notes": (
                    "Always 200 once the service has answered. Bolna retries "
                    "on non-2xx, and a call correctly declined is not a "
                    "delivery failure - answering 5xx loops forever."
                ),
            },
        ),
        _node(
            "Every 15 Minutes", "n8n-nodes-base.scheduleTrigger", [-320, 320],
            {
                "rule": {"interval": [
                    {"field": "minutes", "minutesInterval": DISPATCH_INTERVAL_MINUTES},
                ]},
                "notes": (
                    "Reminders and review requests are queued with a send_after "
                    "and need something to come back for them."
                ),
            },
            type_version=1,
        ),
        _node(
            "Dispatch Due Messages", "n8n-nodes-base.httpRequest", [-100, 320],
            {
                "method": "POST",
                "url": f"{RECEPTIONIST_URL}/messages/dispatch",
                "options": {"retry": {"retryOnFail": True, "maxTries": 2}},
                "notes": (
                    "The service decides what is due, what expired and what a "
                    "cancelled booking cancels. This node only triggers a pass."
                ),
            },
            type_version=4,
        ),
        _node(
            "Alert On Failed Sends", "n8n-nodes-base.if", [140, 320],
            {
                "conditions": {"conditions": [{
                    "leftValue": "={{ $json.failed + $json.expired }}",
                    "rightValue": 0,
                    "operator": {"type": "number", "operation": "gt"},
                }]},
                "notes": (
                    "Expired counts as a fault, not as routine. A message that "
                    "expired means this schedule did not run in time."
                ),
            },
            type_version=2,
        ),
    ]

    connections: dict[str, Any] = {
        "Bolna Post-Call": {"main": [[_to("Ingest Call")]]},
        "Ingest Call": {"main": [[_to("Route Outcome")]]},
        "Route Outcome": {"main": [
            [_to("Booked")],                    # booked
            [_to("Alert Reception")],           # needs_callback
            [_to("Alert Reception")],           # escalated
            [_to("Ignore Incomplete Call")],    # not_actionable
        ]},
        "Booked": {"main": [[_to("Acknowledge")]]},
        "Alert Reception": {"main": [[_to("Acknowledge")]]},
        "Ignore Incomplete Call": {"main": [[_to("Acknowledge")]]},
        "Every 15 Minutes": {"main": [[_to("Dispatch Due Messages")]]},
        "Dispatch Due Messages": {"main": [[_to("Alert On Failed Sends")]]},
    }

    return {
        # Required by `n8n import:workflow` - without it the CLI fails on a
        # NOT NULL constraint against workflow_entity.id. Found by actually
        # importing the file rather than by reading the docs, and a stable
        # value means a re-import updates the workflow instead of creating a
        # duplicate beside it.
        "id": WORKFLOW_ID,
        "name": WORKFLOW_NAME,
        "active": False,
        "nodes": nodes,
        "connections": connections,
        "settings": {"executionOrder": "v1"},
        "pinData": {},
        "tags": [],
        "meta": {
            "setup": (
                "REQUIRED: run n8n with N8N_BLOCK_ENV_ACCESS_IN_NODE=false. "
                "n8n blocks $env in expressions by default, and every URL in "
                "this workflow is an $env reference - blocked, they resolve to "
                "undefined, the HTTP nodes fail with 'access to env vars "
                "denied', and the webhook returns 200 with an empty body while "
                "nothing reaches the service. Then set RECEPTIONIST_URL, "
                "BOLNA_WEBHOOK_SECRET and OPS_ALERT_URL. Verified against "
                "n8n 2.31.7."
            ),
            "description": (
                "Glue only. Every decision that could create an appointment "
                "lives in the receptionist service, which is the only place "
                "the confidence gate and the booking lock can be enforced "
                "together and tested."
            ),
        },
    }


def _to(node: str) -> dict[str, Any]:
    return {"node": node, "type": "main", "index": 0}


def to_json(indent: int = 2) -> str:
    return json.dumps(build_workflow(), indent=indent, ensure_ascii=False) + "\n"
