"""Write the n8n workflow to integrations/n8n/clinic-receptionist.json.

The generated file is committed so a reviewer can import it without running
anything, and regenerated by this script so the JSON and the module that
asserts things about it cannot drift.

    python scripts/export_n8n.py
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from receptionist.integrations.n8n import to_json          # noqa: E402

TARGET = ROOT / "integrations" / "n8n" / "clinic-receptionist.json"


def main() -> None:
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(to_json(), encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
